Models/Assessment/Assignment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LMS.Models.Assessment
{
    public class Assignment
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string SubmissionRequirements { get; set; }
        public string AssignmentRequest { get; set; }
        public int SummId { get; set; }

    }
}

Models/Assessment/DirectQuestion.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LMS.Models.Assessment
{
    public class DirectQuestion
    {
        public int Id { get; set; }
        public string Question { get; set; }
        public string AnswerGuide { get; set; }
    }
}

Models/Assessment/Formative.cs
using LMS.Models.Course;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LMS.Models.Assessment
{
  
    public class Formative
    {        
        
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }

        public string Reference { get; set; }

        public int CourseTopicId { get; set; }

        public int? MultipleChoiceId { get; set; }
        public virtual MultipleChoice MultipleChoice { get; set; }
        public int? TrueFalseId { get; set; }
        public virtual TrueFalse TrueFalse { get; set; }
        [Display(Name = "Type")]
        public string QuestionType { get; set; }
    }
}

Models/Assessment/MultipleChoice.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LMS.Models.Assessment
{
    public class MultipleChoice
    {
        public int Id { get; set; }
        public string Question { get; set; }
        public string AnswerA { get; set; }
        public string AnswerB { get; set; }
        public string AnswerC { get; set; }
        public string AnswerD { get; set; }
        public char CorrectAnswer { get; set; }

    }

}

Models/Assessment/Practical.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LMS.Models.Assessment
{
    public class Practical
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public string Requirements { get; set; }
        public string PracticalRequest { get; set; }
        public int SummId { get; set; }

    }
}

Models/Assessment/Summative.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace LMS.Models.Assessment
{
    public class Summative
    {
        
        public int Id { get; set; }
        [Required]
        public string Title { get; set; }

        public string Reference { get; set; }

        public int CourseUnitId { get; set; }

        public int? MultipleChoiceId { get; set; }
        public virtual MultipleChoice MultipleChoice { get; set; }
        public int? TrueFalseId { get; set; }
        public virtual TrueFalse TrueFalse { get; set; }

        public int? DirectQuestionId { get; set; }
        public virtual DirectQuestion DirectQuestion { get; set; }

        public int? AssignmentId { get; set; }
        public virtual Assignment Assignment { get; set; }

        public int? PracticalId { get; set; }
        public virtual Practical Practical { get; set; }

        [Display(Name = "Type")]
        public string AssessmentType { get; set; }

        public int? Weight { get; set; }



    }
}

Models/Assessment/TrueFalse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LMS.Models.Assessment
{
    public class TrueFalse
    {
        public int Id { get; set; }
        public string Question { get; set; }
        public bool CorrectAnswer { get; set; }

    }
}

Models/ViewModels/AssessmentViewModel.cs
using LMS.Models.Assessment;
using LMS.Models.Course;
using LMS.Models.Learning;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LMS.Models.ViewModels
{
    public class AssessmentViewModel
    {

        public DirectQuestion DirectQuestion { get; set; }
        public Assignment Assignment { get; set; }
        public Practical Practical { get; set; }
        public Summative Summative { get; set; }
        public ApplicationUser Assessor { get; set; }
        public ApplicationUser Learner { get; set; }
        public SummativeSubmission SummativeSubmission { get; set; }
        public IEnumerable <Summative> SummativeList { get; set; }
        public IEnumerable <SummativeSubmission> SubmissionList { get; set; }
        public IEnumerable <DirectQuestion> DirectList { get; set; }
        public IEnumerable <Assignment> AssignmentList { get; set; }
        public IEnumerable <Practical> PracticalList { get; set; }
        public ClassEnrolment ClassEnrolment { get; set; }
        public Dictionary<ClassEnrolment, List<SummativeSubmission>> EnrolSubList { get; set; }
        public Dictionary<SummativeSession, List<SummativeSubmission>> SessionSubList { get; set; }
        public Dictionary<DirectQuestion, SummativeSubmission> QuestSubList { get; set; }

        public IEnumerable<CourseUnit> UnitList { get; set; }
        public IEnumerable<ApplicationUser> Assessors { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string IdNumber { get; set; }
        public string UnitTitle { get; set; }
    }
}

Areas/Learning/Controllers/AssessmentController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using LMS.Data;
using LMS.Extentions;
using LMS.Models;
using LMS.Models.Assessment;
using LMS.Models.Course;
using LMS.Models.Learning;
using LMS.Models.ViewModels;
using LMS.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using NToastNotify;

namespace LMS.Areas.Learning.Controllers
{
    [Area("Learning")]
    public class AssessmentController : Controller
    {
        private ApplicationDbContext _db;
        private UserManager<ApplicationUser> _userManager;
        private IToastNotification _toastNotification;
        private IHostingEnvironment _hosting;


        private Task<ApplicationUser> GetCurrentUserAsync() => _userManager.GetUserAsync(HttpContext.User);

        public AssessmentController(ApplicationDbContext db, UserManager<ApplicationUser> userManager, IToastNotification toastNotification, IHostingEnvironment hosting)
        {
            _db = db;
            _userManager = userManager;
            _toastNotification = toastNotification;
            _hosting = hosting;
        }

        [Authorize(Roles = SD.Assessor)]
        public async Task<IActionResult> AssessorClassList()
        {
            var currentUser = await GetCurrentUserAsync();
            //  var isAssessor = await _userManager.IsInRoleAsync(currentUser, SD.Assessor);

            var classesEnrolled = await _db.ClassEnrolments.Where(p => p.UserRole == SD.Assessor).Where(p => p.UserId == currentUser.Id).ToListAsync();

            ClassViewModel classVM = new ClassViewModel()
            {
                Classes = new List<Class>()
            };
            var classList = new List<Class>();

            foreach (var enrol in classesEnrolled)
            {
                var classe = await _db.Classes.Include(p => p.Course).SingleOrDefaultAsync(p => p.Id == enrol.ClassId);
                classList.Add(classe);
            }

            classVM.Classes = classList;
            return View(classVM);
        }

        [Authorize(Roles = SD.Assessor)]
        public async Task<IActionResult> DirectList(int classId)
        {
            var currentUser = await GetCurrentUserAsync();

            var classesEnrolled = await _db.ClassEnrolments.Include(p => p.Class).Where(p => p.UserRole == SD.Assessor).Where(p => p.UserId == currentUser.Id).ToListAsync();

            var classe = await _db.Classes.SingleOrDefaultAsync(p => p.Id == classId);
            var classeEnrol = classesEnrolled.SingleOrDefault(p => p.ClassId == classe.Id);

            var learnerEnrols = await _db.ClassEnrolments.Where(p => p.ClassId == classId).ToListAsync();

            Dictionary<ClassEnrolment, List<SummativeSubmission>> EnrolSubDirectList = new Dictionary<ClassEnrolment, List<SummativeSubmission>>();

            if (learnerEnrols != null && learnerEnrols.Any())
            {

                foreach (var enrol in learnerEnrols)
                {

                    var questionSubListPerEnrol = await _db.SummativeSubmissions.Include(p => p.SummativeSession).Where(p => p.SummativeSession.ClassEnrolId == enrol.Id).Where(p => p.DirectAnswer != null).ToListAsync();

                    if (questionSubListPerEnrol != null && questionSubListPerEnrol.Any())
                    {

                        EnrolSubDirectList.Add(enrol, questionSubListPerEnrol);
                    }
                }
            }
            AssessmentViewModel assessVM = new AssessmentViewModel()
            {
                EnrolSubList = EnrolSubDirectList,
                ClassEnrolment = await _db.ClassEnrolments.Include(p => p.Class.Course).SingleOrDefaultAsync(p => p.Id == classeEnrol.Id)
            };

            return View(assessVM);
        }

        [Authorize(Roles = SD.Assessor)]
        public async Task<IActionResult> AssignmentList(int classId)
        {
            var currentUser = await GetCurrentUserAsync();

            var classesEnrolled = await _db.ClassEnrolments.Include(p => p.Class).Where(p => p.UserRole == SD.Assessor).Where(p => p.UserId == currentUser.Id).ToListAsync();

            var classe = await _db.Classes.SingleOrDefaultAsync(p => p.Id == classId);
            var classeEnrol = classesEnrolled.SingleOrDefault(p => p.ClassId == classe.Id);

            var learnerEnrols = await _db.ClassEnrolments.Where(p => p.ClassId == classId).ToListAsync();

            Dictionary<ClassEnrolment, List<SummativeSubmission>> EnrolSubAssignmentList = new Dictionary<ClassEnrolment, List<SummativeSubmission>>();

            if (learnerEnrols != null && learnerEnrols.Any())
            {
                foreach (var enrol in learnerEnrols)
                {
                    var assignmentSubListPerEnrol = await _db.SummativeSubmissions.Include(p => p.SummativeSession).Include(p => p.Summative).Where(p => p.SummativeSession.ClassEnrolId == enrol.Id).Where(p => p.AssignmentSubmission != null).ToListAsync();

                    if (assignmentSubListPerEnrol != null && assignmentSubListPerEnrol.Any())
                    {
                        EnrolSubAssignmentList.Add(enrol, assignmentSubListPerEnrol);
                    }
                }
            }
            AssessmentViewModel assessVM = new AssessmentViewModel()
            {
                EnrolSubList = EnrolSubAssignmentList,
                ClassEnrolment = await _db.ClassEnrolments.Include(p => p.Class.Course).SingleOrDefaultAsync(p => p.Id == classeEnrol.Id)
            };

            return View(assessVM);
        }

        [Authorize(Roles = SD.Assessor)]
        public async Task<IActionResult> PracticalList(int classId)
        {
            var currentUser = await GetCurrentUserAsync();

            var classesEnrolled = await _db.ClassEnrolments.Include(p => p.Class).Where(p => p.UserRole == SD.Assessor).Where(p => p.UserId == currentUser.Id).ToListAsync();

            var classe = await _db.Classes.SingleOrDefaultAsync(p => p.Id == classId);
            var classeEnrol = classesEnrolled.SingleOrDefault(p => p.ClassId == classe.Id);

            var learnerEnrols = await _db.ClassEnrolments.Where(p => p.ClassId == classId).ToListAsync();

            Dictionary<ClassEnrolment, List<SummativeSubmission>> EnrolSubPracticalList = new Dictionary<ClassEnrolment, List<SummativeSubmission>>();

            if (learnerEnrols != null && learnerEnrols.Any())
            {

                foreach (var enrol in learnerEnrols)
                {
                    var practicalSubListPerEnrol = await _db.SummativeSubmissions.Include(p => p.SummativeSession).Where(p => p.SummativeSession.ClassEnrolId == enrol.Id).Where(p => p.PracticalSubmission != null).ToListAsync();

                    if (practicalSubListPerEnrol != null && practicalSubListPerEnrol.Count() > 0)
                    {
                        EnrolSubPracticalList.Add(enrol, practicalSubListPerEnrol);
                    }
                }
            }
            AssessmentViewModel assessVM = new AssessmentViewModel()
            {
                EnrolSubList = EnrolSubPracticalList,
                ClassEnrolment = await _db.ClassEnrolments.Include(p => p.Class.Course).SingleOrDefaultAsync(p => p.Id == classeEnrol.Id)
            };

            return View(assessVM);
        }

        [Authorize(Roles = SD.Assessor)]
        public async Task<IActionResult> DirectSessions(int learnerId, int enrolId)
        {

            //Get Assessor Info
            var currentUser = await GetCurrentUserAsync();
            //Get Learner Enrol Info
            var learnerEnrol = await _db.ClassEnrolments.Include(p => p.Class).SingleOrDefaultAsync(p => p.Id == enrolId);
            //Get the Enrolment of the assessor in the class
            var classesEnrolled = await _db.ClassEnrolments.Include(p => p.Class).Where(p => p.UserRole == SD.Assessor).Where(p => p.ClassId == learnerEnrol.ClassId).Where(p => p.UserId == currentUser.Id).ToListAsync();

            var assessors = await _userManager.GetUsersInRoleAsync(SD.Assessor);

            if (classesEnrolled == null)
            {

                return NotFound("The assessor is not enrolled into this class");
            }

            var directSessions = await _db.SummativeSessions.Where(p => p.ClassEnrolId == learnerEnrol.Id).ToListAsync();

            Dictionary<SummativeSession, List<SummativeSubmission>> SessionSubDirectList = new Dictionary<SummativeSession, List<SummativeSubmission>>();

            if (directSessions != null && directSessions.Count() > 0)
            {

                foreach (var session in directSessions)
                {
                    var questionSubListPerSession = await _db.SummativeSubmissions
                        .Include(p => p.SummativeSession)
                        .Include(p => p.Summative)
                        .Where(p => p.SummativeSession.ClassEnrolId == learnerEnrol.Id)
                        .Where(p => p.Summative.AssessmentType == SD.DirectQuestion)
                        .Where(p => p.DirectAnswer != null)
                        .ToListAsync();

                    if (questionSubListPerSession != null && questionSubListPerSession.Count() > 0)
                    {
                        SessionSubDirectList.Add(session, questionSubListPerSession);
                    }
                }
            }
            AssessmentViewModel assessVM = new AssessmentViewModel()
            {
                SessionSubList = SessionSubDirectList,
                ClassEnrolment = await _db.ClassEnrolments.Include(p => p.Class.Course).SingleOrDefaultAsync(p => p.Id == learnerEnrol.Id),
                FirstName = learnerEnrol.UserName,
                LastName = learnerEnrol.UserSurname,
                IdNumber = learnerEnrol.Identity,

Areas/Learning/Views/Assessment/AssessorClassList.cshtml
@using static LMS.Extentions.OrderList
@using LMS.Extentions
@model LMS.Models.ViewModels.ClassViewModel
@{
    ViewData["Title"] = "AssessorClassList";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<br />
<br />

<div class="border backgroundWhite">

    <div class="row">
        <div class="col-6">
            <h2 class="text-info">Assessor Grading Class List</h2>
        </div>
      
    </div>

    <br />
    <div>
        @if (Model.Classes.Count() > 0)
        {
            <table class="table table-sm  table-hover table-bordered table-responsive-sm">

                <tr class="table-primary">
                    <th style="width:28%">
                        @Html.DisplayNameFor(m => m.Class.Name)
                    </th>
                    <th style="width:28%">
                        @Html.DisplayNameFor(m => m.Class.Course)
                    </th>
                    <th style="width:11%;text-align:center">
                        @Html.DisplayNameFor(m => m.Class.StartDate)
                    </th>
                    <th style="width:11%;text-align:center">
                        @Html.DisplayNameFor(m => m.Class.EndDate)
                    </th>
                   
                    <th  colspan="7" cellpadding="2" style="width:3%; text-align:center">
                       Evidence Submission Type
                   </th>

                </tr>
                @foreach (var item in Model.Classes)
                {
            <tr>
                <td>
                    @DisplayLimit.StringLength(item.Name, 50)
                </td>
                <td>
                    @DisplayLimit.StringLength(item.Course.Name, 60)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(m => item.StartDate)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(m => item.EndDate)
                </td>

                <td>
                    <a asp-action="DirectList" asp-route-classId="@item.Id" asp-controller="Assessment" class="btn btn-sm btn-info"><i class="fas fa-tasks"></i>Questioning</a>
                </td>
                <td>
                    <a asp-action="AssignmentList" asp-route-classId="@item.Id" asp-controller="Assessment" class="btn btn-sm btn-success"><i class="fas fa-scroll"></i>Assignments</a>
                </td>
                <td>
                    <a asp-action="PracticalList" asp-route-classId="@item.Id" asp-controller="Assessment" class="btn btn-sm btn-warning"><i class="far fa-building"></i>Practicals</a>
                </td>
            </tr>
                }

            </table>
        }
        else
        {
            <h3>No Classes Exists</h3>
        }
    </div>

</div>

Areas/Learning/Views/Assessment/AssignmentList.cshtml
@using LMS.Extentions
@using LMS.Utility
@using LMS.Models.ViewModels
@model AssessmentViewModel
@{
    ViewData["Title"] = "AssignmentList";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var result = "";
    var counter = 0;
}

<br />

<div class="border backgroundWhite">

    <div class="row">
        <div class="col-8">
            <h2 class="text-info">Assignment Submissions Per Learner</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <p style="padding:5px"><strong>Course:</strong> @Model.ClassEnrolment.Class.Course.Name</p>
        </div>
        <div class="col-6">
            <p style="padding:5px"><strong>Class:</strong> @Model.ClassEnrolment.Class.Name</p>
        </div>
        <div class="col-6 text-right">

        </div>
    </div>

    <br />
    <div>
        @if (Model.EnrolSubList.Count() > 0)
        {
            <table class="table table-striped border table-bordered table-responsive-sm">

                <tr class="table-primary table-sm table-responsive-sm">
                    <th style="width:1%">
                        No
                    </th>
                    <th style="width:25%">
                        Learner Name
                    </th>
                    <th style="width:25%">
                        Learner Surname
                    </th>
                    <th style="width:13%;text-align:center">
                        ID Number
                    </th>
                    <th style="width:10%;text-align:center">
                        Actions
                    </th>
                    <th style="width:11%; text-align:center">
                        Grading Status
                    </th>


                </tr>
                @foreach (var item in Model.EnrolSubList)
                {
                    counter++;
                    foreach (var sub in item.Value)
                    {
                        if (sub.GradePercentage == null) { result = "background:#faede6"; }
                    }
                    <tr style="@result;" class="table-sm table-responsive-sm">
                        <td style="text-align:center">
                            @counter
                        </td>
                        <td>
                            @DisplayLimit.StringLength(item.Key.UserName, 55)
                        </td>
                        <td>
                            @DisplayLimit.StringLength(item.Key.UserSurname, 55)
                        </td>
                        <td style="text-align:center">
                            @Html.DisplayFor(m => item.Key.Identity)

                        <td style="text-align:center" class="hover">
                            <a asp-action="AssignmentSessions" asp-controller="Assessment" asp-route-learnerId="@item.Key.UserId" asp-route-enrolId="@item.Key.Id" class="btn btn-sm btn-warning text-white"><i class="fas fa-file-contract"></i>&nbsp; Edit Grade</a>
                        </td>

                        @if (result != "")
                        {
                            <td style="text-align:center;padding:4px" class="bg-gradient-warning">
                                <p class="bg-gradient-warning text-dark" style="font-weight:600"><i class="fas fa-exclamation-triangle "></i>&nbsp; Incomplete</p>
                            </td>
                        }
                        else
                        {
                            <td style="text-align:center" class="bg-gradient-success">
                                <p class="bg-gradient-success text-dark"><i class="far fa-grin"></i>&nbsp; Complete</p>
                            </td>
                        }


                    </tr>
                }

            </table>
        }
        else
        {
            <h3 class="text-sm-left">There's no Assignment Submissions available at this stage.</h3>
        }
    </div>

</div>

Areas/Learning/Views/Assessment/AssignmentSessions.cshtml
@using LMS.Extentions
@using LMS.Utility
@using LMS.Models.ViewModels
@model AssessmentViewModel
@{
    ViewData["Title"] = "AssignmentSessions";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var result = "";
    var counter = 0;
    var unitList = new List<int>();
}

<br />

<div class="border backgroundWhite">

    <div class="row" style="padding-bottom:10px">
        <div class="col-6">
            <h2 class="text-info">Assignment Sessions per Unit</h2>
        </div>
    </div>
    <div class="row">
        <div class="col-12 ">

            <table style="opacity: 1" class="table table-sm table-striped table-responsive-sm">
                <thead>
                    <tr class="table-secondary table-sm text-dark table-responsive-sm text-center" style="box-shadow: 0 4px 6px 0 rgba(0, 0, 0, 0.1), 0 0px 0px 0 rgba(0, 0, 0, 0.19);">
                        <th style="font-weight:600;color:lightslategray">
                            Name
                        </th>
                        <th style="font-weight:600;color:lightslategray">
                            Surname
                        </th>
                        <th style="font-weight:600;color:lightslategray">
                            Identity
                        </th>
                        <th style="font-weight:600;color:lightslategray">
                            Course
                        </th>
                        <th style="font-weight:600;color:lightslategray">
                            Class
                        </th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="text-center">
                        <td>
                            @Model.FirstName
                        </td>
                        <td>
                            @Model.LastName
                        </td>
                        <td>
                            @Model.IdNumber
                        </td>

                        <td>
                            @Model.ClassEnrolment.Class.Course.Name
                        </td>
                        <td>
                            @Model.ClassEnrolment.Class.Name
                        </td>
                    </tr>
                </tbody>
            </table>

        </div>

    </div>



    <div>
        @if (Model.SessionSubList.Count() > 0)
        {
        <table class="table table-striped border table-bordered table-responsive-sm">

            <tr class="table-primary table-sm table-responsive-sm">
                <th style="width:1%;text-align:center">
                    No
                </th>
                <th style="width:35%">
                    Unit Name
                </th>
                <th style="width:1%">
                    Assignments
                </th>
                <th style="width:7%;text-align:center">
                    Grade Average
                </th>
                <th style="width:7%; text-align:center">
                    Actions
                </th>

            </tr>

            @foreach (var unit in Model.UnitList)            {
             

                @foreach (var sesSubList in Model.SessionSubList.Values)
                {

                    int? grade = 0;

                    foreach (var sub in sesSubList)
                    { 
                        if ((!unitList.Contains(unit.Id)) && unit.SAOrder != null && unit.SAOrder != "" && OrderList.ItemIdOrder(unit.SAOrder).Contains(sub.SummativeId))
                        {
                            counter++;
                            unitList.Add(unit.Id);                          

                            <tr style="@result;" class="table-sm table-responsive-sm">
                                <td style="text-align:center">
                                    @counter
                                </td>
                                <td>
                                    @if (unit.Id == sub.Summative.CourseUnitId)
                                    {
                                        @DisplayLimit.StringLength(unit.Name, 55)
                                    }
                                </td>
                                <td style="text-align:center">
                                    @sesSubList.Where(p => p.Summative.CourseUnitId == unit.Id).Count()

                                </td>
                                <td style="text-align:center">
                          
                                    @(grade / sesSubList.Where(p => p.Summative.CourseUnitId == unit.Id).Count()) %

                                </td>

                                <td style="text-align:center">

                                    <a asp-action="EditGradeAssignment" asp-controller="Assessment" asp-route-sessionId="@sub.SummativeSessionId" class="btn btn-sm btn-danger text-white"><i class="fas fa-edit"></i>&nbsp; Edit Grade</a>

                                </td>

                            </tr>

                        }
                    }
                }}


        </table>
            }
                else
                {
                <h3 class="text-sm-left">There's no Assignment Sessions available at this stage.</h3>
                }
            </div>

        </div>

Areas/Learning/Views/Assessment/DirectList.cshtml
@using LMS.Extentions
@using LMS.Utility
@using LMS.Models.ViewModels
@model AssessmentViewModel
@{
    ViewData["Title"] = "DirectList";
    Layout = "~/Views/Shared/_Layout.cshtml";
    var result = "";
    var counter = 0;
}

<br />

<div class="border backgroundWhite">

    <div class="row">
        <div class="col-8">
            <h2 class="text-info">Questioning Submissions Per Learner</h2>
        </div>
    </div>
        <div class="row">
            <div class="col-6">
                <p style="padding:5px"><strong>Course:</strong> @Model.ClassEnrolment.Class.Course.Name</p>
            </div>
            <div class="col-6">
                <p style="padding:5px"><strong>Class:</strong> @Model.ClassEnrolment.Class.Name</p>
            </div>
        <div class="col-6 text-right">
            
        </div>
    </div>

    <br />
    <div>
        @if (Model.EnrolSubList.Count() > 0)
        {
            <table class="table table-striped border table-bordered table-responsive-sm">

                <tr class="table-primary table-sm table-responsive-sm">
                    <th style="width:1%">
                        No
                    </th>
                    <th style="width:25%">
                        Learner Name
                    </th>
                    <th style="width:25%">
                        Learner Surname
                    </th>
                    <th style="width:13%;text-align:center">
                        ID Number
                    </th>
                    <th style="width:10%;text-align:center">
                        Actions
                    </th>
                    <th style="width:11%; text-align:center">
                      Grading Status
                    </th>


                </tr>
                @foreach (var item in Model.EnrolSubList)
                {
                    counter++;
                    foreach (var sub in item.Value)
                    {
                        if (sub.GradePercentage == null) { result = "background:#faede6"; }
                    }
            <tr style="@result;" class="table-sm table-responsive-sm">
                <td style="text-align:center">
                    @counter
                </td>
                <td>
                    @DisplayLimit.StringLength(item.Key.UserName, 55)
                </td>
                <td>
                    @DisplayLimit.StringLength(item.Key.UserSurname, 55)
                </td>
                <td style="text-align:center">
                    @Html.DisplayFor(m => item.Key.Identity)

                <td style="text-align:center" class="hover">
                    <a asp-action="DirectSessions" asp-controller="Assessment" asp-route-learnerId="@item.Key.UserId" asp-route-enrolId="@item.Key.Id" class="btn btn-sm btn-warning text-white"><i class="fas fa-meh-rolling-eyes"></i>&nbsp; Edit Grade</a>
                </td>
                
                    @if (result != "")
                    {
            <td style="text-align:center;padding:4px" class="bg-gradient-warning">
                <p class="bg-gradient-warning text-dark" style="font-weight:600"><i class="fas fa-exclamation-triangle "></i>&nbsp; Incomplete</p>
            </td>
                        }
                        else
                        {
                    <td style="text-align:center" class="bg-gradient-success">
                        <p class="bg-gradient-success text-dark"><i class="far fa-grin"></i>&nbsp; Complete</p>
                    </td>
                        }
                  

                </tr>
                }

            </table>
        }
        else
        {
    <h3 class="text-sm-left">There's no Direct Question Submissions available at this stage.</h3>
        }
    </div>

</div>